// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbJ60ULqxvovIEs9wEmTN6grotQh-KVA',
    appId: '1:108413745409:web:9a6efc602ec2ff046dc300',
    messagingSenderId: '108413745409',
    projectId: 'crafts-portal',
    authDomain: 'crafts-portal.firebaseapp.com',
    storageBucket: 'crafts-portal.firebasestorage.app',
    measurementId: 'G-XKL4S2LNKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Yrr9kEro4ulPooeC0L-6B0SGnT6gFmQ',
    appId: '1:108413745409:android:8edcee728bf0d4b16dc300',
    messagingSenderId: '108413745409',
    projectId: 'crafts-portal',
    storageBucket: 'crafts-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiNThU13B97v3ZRB9UQ26TvSrmWv9wBc',
    appId: '1:108413745409:ios:fbda2a8a95c22bea6dc300',
    messagingSenderId: '108413745409',
    projectId: 'crafts-portal',
    storageBucket: 'crafts-portal.firebasestorage.app',
    iosBundleId: 'com.example.craftsportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiNThU13B97v3ZRB9UQ26TvSrmWv9wBc',
    appId: '1:108413745409:ios:fbda2a8a95c22bea6dc300',
    messagingSenderId: '108413745409',
    projectId: 'crafts-portal',
    storageBucket: 'crafts-portal.firebasestorage.app',
    iosBundleId: 'com.example.craftsportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmbJ60ULqxvovIEs9wEmTN6grotQh-KVA',
    appId: '1:108413745409:web:3b8d6168645921e66dc300',
    messagingSenderId: '108413745409',
    projectId: 'crafts-portal',
    authDomain: 'crafts-portal.firebaseapp.com',
    storageBucket: 'crafts-portal.firebasestorage.app',
    measurementId: 'G-BWZ696SW6W',
  );
}
